"""
Django settings for planprevencion project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from .settings import * 

DEBUG = config('DEBUG_DEV', cast=bool, default=True)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ppda',
        'USER': config('DB_USER_DEV'),
        'PASSWORD': config('DB_PASSWORD_DEV'),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
