# Generated by Django 5.1.5 on 2025-01-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_largo', models.CharField(max_length=100)),
                ('regulatorio', models.BooleanField(default=True)),
                ('tipo_formula', models.FloatField()),
                ('datos_requeridos', models.CharField(max_length=100)),
                ('formula', models.FloatField()),
                ('umbral_medida', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoPublico',
            fields=[
                ('id_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_organismo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposMedidas',
            fields=[
                ('id_tipo_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_medida', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('calculo_indicador', models.FloatField()),
                ('cumple_requisitos', models.BooleanField(default=True)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('id_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.medida')),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='id_organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.organismopublico'),
        ),
        migrations.AddField(
            model_name='medida',
            name='id_tipo_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.tiposmedidas'),
        ),
    ]
