# Generated by Django 5.1.7 on 2025-03-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='umbral_medida',
        ),
    ]
