# Generated by Django 5.1.5 on 2025-01-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('id_organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.organismopublico')),
            ],
        ),
    ]
