# Generated by Django 5.1.7 on 2025-03-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0002_remove_medida_formula_remove_medida_umbral_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='nombre_corto',
            field=models.CharField(max_length=255),
        ),
    ]
