# Generated by Django 5.1.5 on 2025-01-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0003_usuario_direccion_usuario_rut_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismopublico',
            name='nombre_organismo',
            field=models.CharField(max_length=100),
        ),
    ]
