# Generated by Django 5.1.7 on 2025-03-27 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0003_alter_medida_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='id_tipo_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.tiposmedidas'),
        ),
    ]
