# Generated by Django 5.1.7 on 2025-03-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0004_alter_medida_id_tipo_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.organismopublico'),
        ),
    ]
