# Generated by Django 5.1.5 on 2025-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0004_alter_organismopublico_nombre_organismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
