# Generated by Django 5.1.5 on 2025-03-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0006_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismopublico',
            name='only_admin',
            field=models.BooleanField(default=False),
        ),
    ]
