# Generated by Django 5.1.7 on 2025-03-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0006_usuario_aprobado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_organismo',
            new_name='organismo',
        ),
    ]
