# Generated by Django 5.1.7 on 2025-03-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0007_rename_id_organismo_usuario_organismo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='id_medida',
            new_name='medida',
        ),
        migrations.RenameField(
            model_name='medida',
            old_name='id_organismo',
            new_name='organismo',
        ),
        migrations.RenameField(
            model_name='medida',
            old_name='id_tipo_medida',
            new_name='tipo_medida',
        ),
    ]
