# Generated by Django 5.1.7 on 2025-03-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0008_rename_id_medida_indicador_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunaplan',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organismopublico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiposmedidas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
