# Generated by Django 5.1.7 on 2025-03-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0009_comunaplan_activo_medida_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='proxima_fecha_carga',
            field=models.DateField(blank=True, null=True),
        ),
    ]
