# Generated by Django 5.1.7 on 2025-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0011_remove_indicador_data_remove_medida_datos_requeridos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
